name: "Windows CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Swift
        uses: mxcl/setup-swift@v1
        with:
          version: '5.5.0'
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
