name: "Windows CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Swift
        uses: apple/setup-swift@v2.2.3
        with:
          swift-version: '5.5.0'
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
